# Generated by Django 3.0.8 on 2020-07-27 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month_name', models.CharField(max_length=30)),
                ('day_name', models.CharField(max_length=50)),
                ('month_number', models.IntegerField()),
                ('week_number', models.IntegerField()),
                ('year_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('mrr_date', models.DateField(null=True)),
                ('optiplan_date', models.DateField(null=True)),
                ('eliminate_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('create_att', models.DateTimeField(auto_now_add=True)),
                ('updated_att', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('create_att', models.DateTimeField(auto_now_add=True)),
                ('updated_att', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('create_att', models.DateTimeField(auto_now_add=True)),
                ('updated_att', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('create_att', models.DateTimeField(auto_now_add=True)),
                ('updated_att', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('line', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('create_att', models.DateTimeField(auto_now_add=True)),
                ('updated_att', models.DateTimeField(auto_now=True)),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_planeacion.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Mo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(max_length=10)),
                ('entry_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('order_qty', models.IntegerField()),
                ('received_qty', models.IntegerField()),
                ('project', models.CharField(blank=True, max_length=50, null=True)),
                ('fiscal_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analisis_planeacion.FiscalCalendar')),
                ('schedule_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analisis_planeacion.Schedule')),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_planeacion.Sku')),
                ('workcenter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_planeacion.WorkCenter')),
            ],
        ),
        migrations.CreateModel(
            name='FabricShortage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcs_to_issue', models.IntegerField()),
                ('pcs_short', models.IntegerField()),
                ('no_fabric', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('create_att', models.DateTimeField(auto_now_add=True)),
                ('updated_att', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_planeacion.Sku')),
                ('workcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_planeacion.WorkCenter')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('planner', models.CharField(max_length=50)),
                ('spreading', models.CharField(max_length=50)),
                ('position', models.FloatField()),
                ('grand_total', models.IntegerField()),
                ('create_att', models.DateTimeField(auto_now_add=True)),
                ('updated_att', models.DateTimeField(auto_now=True)),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_planeacion.Sku')),
                ('subgroup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_planeacion.Subgroup')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_planeacion.Warehouse')),
                ('workcenter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analisis_planeacion.WorkCenter')),
            ],
            options={
                'unique_together': {('name', 'planner', 'warehouse_id', 'subgroup_id', 'sku_id')},
            },
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=50)),
                ('sah_avg', models.FloatField()),
                ('sah_goal', models.FloatField()),
                ('comments', models.CharField(blank=True, max_length=50)),
                ('create_att', models.DateTimeField(auto_now_add=True)),
                ('updated_att', models.DateTimeField(auto_now=True)),
                ('workcenter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_planeacion.WorkCenter')),
            ],
            options={
                'unique_together': {('period', 'status', 'workcenter_id')},
            },
        ),
    ]
